spring:
  datasource:
    url: jdbc:mysql://localhost:3306/motorcycle_shop?useSSL=false&serverTimezone=UTC
    username: motorcycle
    password: motorcycle
    initialization-mode: always
    schema:
      - classpath:/sql/schema.sql
    data:
      - classpath:/sql/data.sql
