spring:
  datasource:
    url: jdbc:mysql://localhost:3306/motorcycle_shop?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8
    username: motorcycle
    password: motorcycle
    initialization-mode: always
    schema:
      - classpath:/sql/schema.sql
    data:
      - classpath:/sql/data.sql
    thymeleaf:
      cache: false
